/*CREATE TABLE `PERSON` (
`ID` INTEGER IDENTITY PRIMARY KEY ,
`NAME` VARCHAR(255) NOT NULL
);

CREATE TABLE `DOCUMENT` (
`ID` INTEGER IDENTITY PRIMARY KEY ,
`NAME` VARCHAR(255) NOT NULL,
`CODE` VARCHAR (255) NOT NULL
);

CREATE TABLE `PERSON_DOCUMENT` (
`PERSON_ID` INTEGER NOT NULL,
`DOCUMENT_ID` INTEGER NOT NULL
);
*/

CREATE TABLE person (id SERIAL PRIMARY KEY, name VARCHAR(255));
CREATE TABLE document (id SERIAL PRIMARY KEY, name VARCHAR(255), code VARCHAR(255));
CREATE TABLE person_document (person_id INTEGER, document_id INTEGER);
